//
// BeerIngredientsHops.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BeerIngredientsHops: Codable, JSONEncodable {

    public var name: String?
    public var amount: BeerVolume?
    public var add: String?
    public var attribute: String?

    public init(name: String? = nil, amount: BeerVolume? = nil, add: String? = nil, attribute: String? = nil) {
        self.name = name
        self.amount = amount
        self.add = add
        self.attribute = attribute
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case amount
        case add
        case attribute
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(add, forKey: .add)
        try container.encodeIfPresent(attribute, forKey: .attribute)
    }
}

