//
// BeerMethodMashTemp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BeerMethodMashTemp: Codable, JSONEncodable {

    public var temp: BeerVolume?
    public var duration: Double?

    public init(temp: BeerVolume? = nil, duration: Double? = nil) {
        self.temp = temp
        self.duration = duration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case temp
        case duration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(temp, forKey: .temp)
        try container.encodeIfPresent(duration, forKey: .duration)
    }
}

