//
// BeerMethodFermentation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BeerMethodFermentation: Codable, JSONEncodable {

    public var temp: BeerVolume?

    public init(temp: BeerVolume? = nil) {
        self.temp = temp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case temp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(temp, forKey: .temp)
    }
}

