//
// BeerVolume.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BeerVolume: Codable, JSONEncodable {

    public var value: Double?
    public var unit: String?

    public init(value: Double? = nil, unit: String? = nil) {
        self.value = value
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(value, forKey: .value)
        try container.encodeIfPresent(unit, forKey: .unit)
    }
}

