//
// BeerIngredientsMalt.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BeerIngredientsMalt: Codable, JSONEncodable {

    public var name: String?
    public var amount: BeerVolume?

    public init(name: String? = nil, amount: BeerVolume? = nil) {
        self.name = name
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(amount, forKey: .amount)
    }
}

