//
// ErrorBeerData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ErrorBeerData: Codable, JSONEncodable {

    public var location: String?
    public var param: String?
    public var msg: String?
    public var value: String?

    public init(location: String? = nil, param: String? = nil, msg: String? = nil, value: String? = nil) {
        self.location = location
        self.param = param
        self.msg = msg
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case location
        case param
        case msg
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encodeIfPresent(param, forKey: .param)
        try container.encodeIfPresent(msg, forKey: .msg)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

