//
// ForecastSources.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ForecastSources: Codable, JSONEncodable {

    public var title: String?
    public var slug: String?
    public var url: String?
    public var crawlRate: Double?

    public init(title: String? = nil, slug: String? = nil, url: String? = nil, crawlRate: Double? = nil) {
        self.title = title
        self.slug = slug
        self.url = url
        self.crawlRate = crawlRate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case slug
        case url
        case crawlRate = "crawl_rate"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(slug, forKey: .slug)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(crawlRate, forKey: .crawlRate)
    }
}

